"""add_primary_score_to_exam_attempts

Revision ID: 40972093e74a
Revises: be4ecf10ec19
Create Date: 2026-03-04 20:43:28.026704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40972093e74a'
down_revision: Union[str, None] = 'be4ecf10ec19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_attempts', sa.Column('primary_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_attempts', 'primary_score')
    # ### end Alembic commands ###
