"""add_task_fields_and_user_last_active

Revision ID: 6946206e42ef
Revises: b8587d44b910
Create Date: 2026-03-03 23:32:55.127122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6946206e42ef'
down_revision: Union[str, None] = 'b8587d44b910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type manually
    task_difficulty = postgresql.ENUM('easy', 'medium', 'hard', name='taskdifficulty')
    task_difficulty.create(op.get_bind())

    op.add_column('tasks', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('description', sa.Text(), nullable=True))
    
    # Add difficulty as nullable first
    op.add_column('tasks', sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='taskdifficulty'), nullable=True))
    # Update existing rows
    op.execute("UPDATE tasks SET difficulty = 'easy' WHERE difficulty IS NULL")
    # Set to NOT NULL
    op.alter_column('tasks', 'difficulty', nullable=False)

    op.add_column('tasks', sa.Column('solution_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active_at')
    op.drop_column('tasks', 'solution_steps')
    op.drop_column('tasks', 'difficulty')
    op.drop_column('tasks', 'description')
    op.drop_column('tasks', 'title')

    # Drop enum type manually
    task_difficulty = postgresql.ENUM('easy', 'medium', 'hard', name='taskdifficulty')
    task_difficulty.drop(op.get_bind())
    # ### end Alembic commands ###

