"""add real name fields to user

Revision ID: 8553a603b242
Revises: 6946206e42ef
Create Date: 2026-03-04 12:28:24.673452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8553a603b242'
down_revision: Union[str, None] = '6946206e42ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name_real', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_name_real', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name_real')
    op.drop_column('users', 'first_name_real')
    # ### end Alembic commands ###
