"""add_ege_number_to_topics

Revision ID: 8afce74e202e
Revises: d98b5cbe4061
Create Date: 2026-03-14 10:41:15.067503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8afce74e202e'
down_revision: Union[str, None] = 'd98b5cbe4061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('ege_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'ege_number')
    # ### end Alembic commands ###
