"""add_full_solution_code_to_tasks

Revision ID: cf7f1c1ef3ae
Revises: 40972093e74a
Create Date: 2026-03-04 22:34:27.042738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf7f1c1ef3ae'
down_revision: Union[str, None] = '40972093e74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('full_solution_code', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'full_solution_code')
    # ### end Alembic commands ###
