server {
    listen 80;
    server_name rancheasy.ru;

    # Certbot challenge location
    location /.well-known/acme-challenge/ {
        root /var/lib/letsencrypt/;
    }

    # Временно разрешаем HTTP, чтобы зайти на сайт или просто пройти проверку
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        rewrite ^/api/(.*) /$1 break;
    }
}

# Блок 443 временно удален/закомментирован, так как нет сертификатов
